name: Build and Push Container Image

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to ghcr
      run: echo ${{ secrets.GITHUB_TOKEN }} | buildah login --username ${{ github.actor }} --password-stdin ghcr.io

    - name: Run build script
      run: bash buildah_scripts/build.sh

    - name: Push image
      run: buildah push simline:latest ghcr.io/${{ github.repository }}:${{ github.ref }}